CASM-3518: Use stable version of cray-product-catalog
Cray-HPE/cray-nls pull request #103
Opened 2022-11-22 18:36 UTC by ekamin-hpe

* Resolves CASM-3518

## Testing

Tested by pulling the new image

- [X] Version number(s) incremented, if applicable
- [X] Copyrights updated
- [X] License file intact
- [X] Target branch correct
- [X] CHANGELOG.md updated
- [X] Testing is appropriate and complete, if applicable
- [X] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-11-22 18:36 UTC, ekamin-hpe commented
I am not sure this goes into the container image, so wasn't sure what (if any) version numbers need updating with this change.

2022-11-22 19:44 UTC, dzou-hpe requested changes
i am going to block this for now until i figure out why...

for whatever reason, this template is not loading into k8s. i will need a few more minutes to debug that

2022-11-22 19:47 UTC, dzou-hpe commented
> i am going to block this for now until i figure out why...
> 
> for whatever reason, this template is not loading into k8s. i will need a few more minutes to debug that

@ekamin-hpe  so we have this in our code... `list, err := fs.Glob(argoWorkflowTemplateFS, "**/*.template.argo.yaml")` which means we only upload workflows end with `.template.argo.yaml`. you can change this code to be any yaml or rename your file....

2022-11-22 22:39 UTC, haasken-hpe approved these changes

2022-11-23 02:19 UTC, dzou-hpe approved these changes

2022-11-23 15:20 UTC, merged