CASMINST-6734: SW_ADMIN_PASSWORD variable is not required to be set for tests anymore
Cray-HPE/cray-nls pull request #219
Opened 2024-11-25 09:16 UTC by Srinivas-Anand-HPE

## Summary and Scope

Goss tests no longer need the switch admin password set using an environment variable. The tests read the value directly from Vault now.

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves CASMINST-6734
* Documentation changes required in 

## Testing

### Tested on:

  * Starlord

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?

- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?

## Pull Request Checklist

- [X] Version number(s) incremented, if applicable
- [X] Copyrights updated
- [ ] License file intact
- [X] Target branch correct
- [ ] CHANGELOG.md updated
- [X] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2024-11-25 09:24 UTC, Pankhuri-Rajesh commented on src/api/models/nls/ncn_reboot.go
> + *  (C) Copyright 2022,2024 Hewlett Packard Enterprise Development LP
I think there should be a hyphen instead of comma. (2022-2024) .
Same goes for other files as well

2024-12-02 17:59 UTC, leliasen-hpe approved these changes

2024-12-03 04:49 UTC, Pankhuri-Rajesh requested changes

2024-12-03 04:49 UTC, Pankhuri-Rajesh commented on .version
> -4.1.0
version change is not required since this should go in 4.1.1

2024-12-03 04:49 UTC, Pankhuri-Rajesh commented on src/api/argo-templates/_test_data_/worker.post-rebuild.yaml
> +# (C) Copyright 2022,2024 Hewlett Packard Enterprise Development LP
should it be 2022-2024 instead?

2024-12-03 04:49 UTC, Pankhuri-Rajesh commented on src/api/argo-templates/render.go
> + *  (C) Copyright 2022,2024 Hewlett Packard Enterprise Development LP
2022-2024

2024-12-03 04:49 UTC, Pankhuri-Rajesh commented on src/api/argo-templates/render_test.go
> + *  (C) Copyright 2022,2024 Hewlett Packard Enterprise Development LP
2022-2024

2024-12-03 04:57 UTC, Pankhuri-Rajesh approved these changes

2024-12-03 05:10 UTC, rajeshranganathan-hpe approved these changes

2024-12-04 05:12 UTC, merged