First pass at updating README added two new steps
Cray-HPE/cray-nls pull request #40
Opened 2022-06-01 19:15 UTC by EthanHolen

## Summary and Scope

_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_

Added steps for development setup to the main README.md file

_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_

Documentation

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

N/A

* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

_List the environments in which these changes were tested._

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2022-06-01 19:21 UTC, dzou-hpe requested changes

2022-06-01 19:21 UTC, dzou-hpe commented on README.md
> +    kubectl get nodes
you don't need this, i was just using this to confirm you have k3d created

2022-06-01 21:12 UTC, dzou-hpe approved these changes

2022-06-01 21:12 UTC, dzou-hpe commented on README.md
> +     kubectl edit ClusterRoleBindings/cluster-admin
FYI, this could be done by a patch cmd instead of manually modifying here.

2022-06-02 16:15 UTC, dzou-hpe approved these changes

2022-06-02 18:03 UTC, EthanHolen commented
Hey @dzou-hpe I was going to merge earlier but it looks like the license check is hanging or something and I'm not sure why

2022-06-02 18:11 UTC, merged